/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-02-22 14:16:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class About_0020Us_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/Views/header.jsp", Long.valueOf(1486968877269L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/About Us.css\">\r\n");
      out.write("\r\n");
      out.write("\t<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"background-color:#E8E8E8;\">\r\n");
      out.write("\t<div style=\"margin-left:0px;margin-top:0px;\" class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("  \t<div class=\"col-lg-4\">\r\n");
      out.write("  \t<img style=\"width:105%; height:150px;\" class=\"img-responsive\" src=\"Resources/Images/logo.png\"  alt=\"shoes logo\"></img>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t<div  class=\"col-lg-8\">\r\n");
      out.write("  \t<img style=\"width:122%; height:150px; class=\"img-responsive\" src=\"Resources/Images/mainBanner.jpg\"  alt=\"banner\"></img>\r\n");
      out.write("  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed\">\r\n");
      out.write("   \t<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("     \t<a class=\"navbar-brand\" style=\"font-size:15px;\" href=\"home\">HOME\r\n");
      out.write("     \t<span class=\"glyphicon glyphicon-home\" style=\" font-size:15px; color:black;\"></span></a>\r\n");
      out.write("    </div> \r\n");
      out.write("    \t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\"> \r\n");
      out.write("   \t\t  <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write(" \t\t        <li ><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">MEN <span class=\"caret\"></span>\r\n");
      out.write(" \t\t        <img width=\"22px\" src=\"Resources/Images/fi-male.svg\" ></a>\r\n");
      out.write("        \t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("        \t\t<li><a href=\"#\">Canvas</a></li>\r\n");
      out.write("        \t\t<li><a href=\"#\">Sneakers</a></li>\r\n");
      out.write("        \t\t<li><a href=\"#\">Leather</a></li>\r\n");
      out.write("        \t\t</ul>\r\n");
      out.write("        \t\t</li>\r\n");
      out.write("        \t\t <li><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">WOMEN <span class=\"caret\"></span>\r\n");
      out.write("        \t\t<img width=\"22px\"src=\"Resources/Images/fi-female.svg\" ></a>\r\n");
      out.write("        \t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("        \t\t<li><a href=\"#\">Canvas</a></li>\r\n");
      out.write("        \t\t<li><a href=\"#\">Sneakers</a></li>\r\n");
      out.write("        \t\t<li><a href=\"#\">Leather</a></li>\r\n");
      out.write("        \t\t</ul>\r\n");
      out.write("        \t\t</li>\r\n");
      out.write("        \t\t<li><a href=\"#\">SALE\r\n");
      out.write("         \t\t<span class=\"glyphicon glyphicon-gift\" style=\"color:black;\"></span></a></li>\r\n");
      out.write("         \t\t<li><a href=\"login\">LOGIN\r\n");
      out.write("         \t\t<span class=\"glyphicon glyphicon-log-in\" style=\"color:black;\"></span></a></li>\r\n");
      out.write("         \t\t<li><a href=\"aboutus\">ABOUT US\r\n");
      out.write("         \t\t <span class=\"glyphicon glyphicon-user\" style=\"color:black;\"></span></a></li>\r\n");
      out.write("         \t\t<li><a href=\"contactus\">CONTACT US\r\n");
      out.write("         \t\t<span class=\"glyphicon glyphicon-phone\" style=\"color:black;\"></span></a></li>\r\n");
      out.write("      \t</ul>\r\n");
      out.write("    </div>\r\n");
      out.write(" </div> \r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body{background-color:#FFBF00;}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <section style=\"height:80px;\"></section>\r\n");
      out.write("\t<div class=\"row\" style=\"text-align:center;\">\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div class=\"col-md-10 footer-nav animated fadeInUp\">\r\n");
      out.write("            \t<h2>ABOUT US</h2>\r\n");
      out.write("            \t<div class=\"col-md-10\">\r\n");
      out.write("                    <ul class=\"pages\">\r\n");
      out.write("                    <h4>WHO WE ARE?</h4>\r\n");
      out.write("\t\t\t\t\t<p>A group of people who got together to create footwear, but got high on style somewhere in between, started watching fashion networks and created something that can be recognized only by someone out of this planet. That's how we started and that's how we are still going on.\r\n");
      out.write("\t\t\t\t\tWe are India's one of its kind online personalized store with a group of stylists to recommend you the most stylish footwear as per your needs. We bring you a huge collection, created around many themes and styles to bring you cult classic fashion.</p>\r\n");
      out.write("                    <h4>WHAT WE DO?</h4>\r\n");
      out.write("\t\t\t\t\t<p>\tWell, to start with - Everything to make you feel Special! A stylist to discuss your fashion needs, a delivery guarantee, and no question asked return/exchange policy and a promise to ensure quality in all our products. We believe in outrageous fashion trends and offer you the same, but with a hint of class. Our famous fashion advice for all is: Don't just be Stylish, Be Smart, buy SMART on FASHOS.com!</p>\r\n");
      out.write("\t\t\t\t\t<h4>HOW TO GET IT GOING:</h4>\t\r\n");
      out.write("\t\t\t\t\t<p>Welcome to the world of FASHOS - a smart, quick and easy way to get yourself access to the latest fasionista. All you need to do is access our online storefront and fill out a brief survey to help us know your personal style needs and preferences. Once you tell us what you like, our team of stylists will take you to an exciting journey, showing you the variety we boast of and will help you choose the best. And believe us â online shopping at FASHOS is a lot of fun, not even a bit of it will disappoint you.</p>\r\n");
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("<h5>Bacca Bucci Bachini Bruno Manetti Converse Delize Fausto Foot 'N' Style Franco Leone Freetoes Funk Get Glamr Hitz Jolly Jolla Kielz La Briza La Isla Lancer Lee Cooper Lotto Maiden Doll Marc Loire  Marco Ferro Mocas Numero Uno Provogue Red Chief Salt 'N' Pepper San Vertino Steppings Studio S Style Centrum Ten Woodland\r\n");
      out.write("All Categories</h5>\r\n");
      out.write("<h6>Women â Casual Formal Slippers Sandal Sports Flat Men â Casual Formal Slipper Sandal Sports Sale â Womens Sale Mens Sale\r\n");
      out.write("Â© 2016 FASHOS.COM All Rights Reserved.</h6>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t</div>                         \r\n");
      out.write("     </div>   \r\n");
      out.write("     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
