/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2017-02-22 05:29:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/Views/footer.jsp", Long.valueOf(1486700606694L));
    _jspx_dependants.put("/WEB-INF/Views/header.jsp", Long.valueOf(1486968877269L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"background-color:#E8E8E8;\">\r\n");
      out.write("\t<div style=\"margin-left:0px;margin-top:0px;\" class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("  \t<div class=\"col-lg-4\">\r\n");
      out.write("  \t<img style=\"width:105%; height:150px;\" class=\"img-responsive\" src=\"Resources/Images/logo.png\"  alt=\"shoes logo\"></img>\r\n");
      out.write("  \t</div>\r\n");
      out.write("  \t<div  class=\"col-lg-8\">\r\n");
      out.write("  \t<img style=\"width:122%; height:150px; class=\"img-responsive\" src=\"Resources/Images/mainBanner.jpg\"  alt=\"banner\"></img>\r\n");
      out.write("  \t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-fixed\">\r\n");
      out.write("   \t<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("     \t<a class=\"navbar-brand\" style=\"font-size:15px;\" href=\"home\">HOME\r\n");
      out.write("     \t<span class=\"glyphicon glyphicon-home\" style=\" font-size:15px; color:black;\"></span></a>\r\n");
      out.write("    </div> \r\n");
      out.write("    \t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\"> \r\n");
      out.write("   \t\t  <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write(" \t\t        <li ><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">MEN <span class=\"caret\"></span>\r\n");
      out.write(" \t\t        <img width=\"22px\" src=\"Resources/Images/fi-male.svg\" ></a>\r\n");
      out.write("        \t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("        \t\t<li><a href=\"#\">Canvas</a></li>\r\n");
      out.write("        \t\t<li><a href=\"#\">Sneakers</a></li>\r\n");
      out.write("        \t\t<li><a href=\"#\">Leather</a></li>\r\n");
      out.write("        \t\t</ul>\r\n");
      out.write("        \t\t</li>\r\n");
      out.write("        \t\t <li><a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">WOMEN <span class=\"caret\"></span>\r\n");
      out.write("        \t\t<img width=\"22px\"src=\"Resources/Images/fi-female.svg\" ></a>\r\n");
      out.write("        \t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("        \t\t<li><a href=\"#\">Canvas</a></li>\r\n");
      out.write("        \t\t<li><a href=\"#\">Sneakers</a></li>\r\n");
      out.write("        \t\t<li><a href=\"#\">Leather</a></li>\r\n");
      out.write("        \t\t</ul>\r\n");
      out.write("        \t\t</li>\r\n");
      out.write("        \t\t<li><a href=\"#\">SALE\r\n");
      out.write("         \t\t<span class=\"glyphicon glyphicon-gift\" style=\"color:black;\"></span></a></li>\r\n");
      out.write("         \t\t<li><a href=\"login\">LOGIN\r\n");
      out.write("         \t\t<span class=\"glyphicon glyphicon-log-in\" style=\"color:black;\"></span></a></li>\r\n");
      out.write("         \t\t<li><a href=\"aboutus\">ABOUT US\r\n");
      out.write("         \t\t <span class=\"glyphicon glyphicon-user\" style=\"color:black;\"></span></a></li>\r\n");
      out.write("         \t\t<li><a href=\"contactus\">CONTACT US\r\n");
      out.write("         \t\t<span class=\"glyphicon glyphicon-phone\" style=\"color:black;\"></span></a></li>\r\n");
      out.write("      \t</ul>\r\n");
      out.write("    </div>\r\n");
      out.write(" </div> \r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("    $('#myCarousel').carousel({\r\n");
      out.write("        interval: 10000\r\n");
      out.write("    })\r\n");
      out.write("    $('.fdi-Carousel .item').each(function () {\r\n");
      out.write("        var next = $(this).next();\r\n");
      out.write("        if (!next.length) {\r\n");
      out.write("            next = $(this).siblings(':first');\r\n");
      out.write("        }\r\n");
      out.write("        next.children(':first-child').clone().appendTo($(this));\r\n");
      out.write("\r\n");
      out.write("        if (next.next().length > 0) {\r\n");
      out.write("            next.next().children(':first-child').clone().appendTo($(this));\r\n");
      out.write("        }\r\n");
      out.write("        else {\r\n");
      out.write("            $(this).siblings(':first').children(':first-child').clone().appendTo($(this));\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/index.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color:#45D4FF\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <br>\r\n");
      out.write("  <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("    </ol>\r\n");
      out.write("\r\n");
      out.write("    <!-- Wrapper for slides -->\r\n");
      out.write("    <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item active\">\r\n");
      out.write("        <img src=\"Resources/Images/shoes01.jpg\" alt=\"shoes\" width=\"660\" height=\"345\">\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"Resources/Images/shoes02.jpg\" alt=\"shoes\" width=\"660\" height=\"345\">\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("        <img src=\"Resources/Images/shoes03.jpg\" alt=\"shoes\" width=\"660\" height=\"345\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Left and right controls -->\r\n");
      out.write("    <a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Next</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"span12\">\r\n");
      out.write("                <div class=\"well\">\r\n");
      out.write("                    <div id=\"myCarousel\" class=\"carousel fdi-Carousel slide\">\r\n");
      out.write("                     <!-- Carousel items -->\r\n");
      out.write("                        <div class=\"carousel fdi-Carousel slide\" id=\"eventCarousel\" data-interval=\"0\">\r\n");
      out.write("                            <div class=\"carousel-inner onebyone-carosel\">\r\n");
      out.write("                                <div class=\"item active\">\r\n");
      out.write("                                 <div class=\"item\">\r\n");
      out.write("                                    <div class=\"col-md-4\">\r\n");
      out.write("                                        <a href=\"#\"><img src=\"Resources/Images/office.jpg\" class=\"img-responsive center-block\"></a>\r\n");
      out.write("                                        <div class=\"text-center\">1</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <div class=\"col-md-4\">\r\n");
      out.write("                                        <a href=\"#\"><img src=\"Resources/Images/wedges.jpg\" class=\"img-responsive center-block\"></a>\r\n");
      out.write("                                        <div class=\"text-center\">2</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <div class=\"col-md-4\">\r\n");
      out.write("                                        <a href=\"#\"><img src=\"Resources/Images/sports.jpg\" class=\"img-responsive center-block\"></a>\r\n");
      out.write("                                        <div class=\"text-center\">3</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"item\">\r\n");
      out.write("                                    <div class=\"col-md-4\">\r\n");
      out.write("                                        <a href=\"#\"><img src=\"Resources/Images/travel_adventure.jpg\" class=\"img-responsive center-block\"></a>\r\n");
      out.write("                                        <div class=\"text-center\">4</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a class=\"left carousel-control\" href=\"#eventCarousel\" data-slide=\"prev\"></a>\r\n");
      out.write("                            <a class=\"right carousel-control\" href=\"#eventCarousel\" data-slide=\"next\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--/carousel-inner-->\r\n");
      out.write("                    </div><!--/myCarousel-->\r\n");
      out.write("                </div><!--/well-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Resources/css/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <section style=\"height:80px;\"></section>\r\n");
      out.write("\t<div class=\"row\" style=\"text-align:center;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("    <footer class=\"footer-bs\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("        \t<div class=\"col-md-3 footer-brand animated fadeInLeft\">\r\n");
      out.write("   \t\t\t     \t\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-4 footer-nav animated fadeInUp\">\r\n");
      out.write("            \t<h4>Menu</h4>\r\n");
      out.write("            \t<div class=\"col-md-6\">\r\n");
      out.write("                    <ul class=\"pages\">\r\n");
      out.write("                        <li><a href=\"#\">Travel</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Nature</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Explores</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Science</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Advice</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            \t<div class=\"col-md-6\">\r\n");
      out.write("                    <ul class=\"list\">\r\n");
      out.write("                        <li><a href=\"About Us.jsp\">About Us</a></li>\r\n");
      out.write("                        <li><a href=\"Contact Us.jsp\">Contacts</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Terms & Condition</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-2 footer-social animated fadeInDown\">\r\n");
      out.write("            \t<h4>Follow Us</h4>\r\n");
      out.write("            \t<ul>\r\n");
      out.write("                \t<li><a href=\"#\">Facebook</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">Twitter</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">Instagram</a></li>\r\n");
      out.write("                \t<li><a href=\"#\">RSS</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        \t<div class=\"col-md-3 footer-ns animated fadeInRight\">\r\n");
      out.write("            \t<h4>Newsletter</h4>\r\n");
      out.write("\r\n");
      out.write("                <p>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                      <input type=\"text\" class=\"form-control\" placeholder=\"Search for...\">\r\n");
      out.write("                      <span class=\"input-group-btn\">\r\n");
      out.write("                        <button class=\"btn btn-default\" type=\"button\"><span class=\"glyphicon glyphicon-envelope\"></span></button>\r\n");
      out.write("                      </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <section style=\"text-align:center; margin:10px auto;\"><p><b>Designed by DHEERAJ</b></p></section>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
